### ISSUE TITLE
Add support for queries in list endpoints

### ISSUE THREAD

**Issue by frankli0324** [CTFd/CTFd.js#10]
`ChallengeList`, for example:

`/api/v1/challenges?q=WEB&field=category`

expected:

```js
CTFd.pages.challenges.getChallenges({category: "WEB"});
```

and since CTFd doesn't support multiple query conditions on such endpoints (yet?), maybe some check is needed

**Comment by ColdHeat** [comment]
This would be a good improvement. I would accept a PR if you could put one up.

**Comment by ColdHeat** [comment]
Closed in #14
